#!/usr/bin/env python
# -*-coding: utf-8 -*-
"""
Monitor an Asterisk Manager Interface and provide popup notification of
incoming calls.

callPopPy will attempt to look up the incoming number in a SQLite database
and notify the name associated with the caller. Maintaining the SQLite
database is a job for something else - a Thunderbird extension, Squalit,
exists to do this from a Thunderbird address book.

Copyright 2011 Chris Hastie

Contains code originally released as pyCalledMe by Olivier H. Beauchesne
and Copyright 2009 Olivier H. Beauchesne
http://olihb.com/2010/08/08/incoming-call-popup-under-ubuntu-and-asterisk/

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

__version_info__ = ('0', '1', '0rc2')
__version__ = '.'.join(__version_info__)


from twisted.internet import gtk2reactor
gtk2reactor.install(True)

from twisted.internet import reactor, defer
from twisted.internet.protocol import ReconnectingClientFactory
from starpy.manager import AMIProtocol
from twisted.internet import task
import logging
import logging.handlers
import sys
import os
import os.path
from cgi import escape
from pysqlite2 import dbapi2 as sqlite
import ConfigParser

hasGnome = True
try:
  import gnome.ui
except:
  hasGnome = False



class CallPopFactory(ReconnectingClientFactory):
    """ Factory for connection. Subclassed from ReconnectingClientFactory
    to take advantage of backing off reconnection times
    """
    protocol = AMIProtocol
    connect_callback=None

    def __init__(self, username, secret, server='localhost', port=5038):
        self.username = username
        self.secret = secret
        self.server = server
        self.port = port

    def login( self, ip='localhost', port=5038, timeout=5 ):
        self.loginDefer = defer.Deferred()
        reactor.connectTCP(ip,port,self, timeout=timeout)
        return self.loginDefer

    def clientConnectionFailed(self, connector, reason):
        log.warning( 'Connection failed. Reason: %s', reason)
        ReconnectingClientFactory.clientConnectionFailed(self, self, reason)

    def clientConnectionLost(self, connector, reason):
        log.warning( 'Lost connection. Reason: %s', reason)
        ReconnectingClientFactory.clientConnectionLost(self, self, reason)

    def connect(self):
        log.info("Connecting to Asterisk at %s:%d", self.server, self.port)
        df = self.login(self.server, self.port)
        if self.connect_callback!=None:
            df.addCallback(self.connect_callback)

class Popup:
  """ Abstraction layer to handle popup notifications. Provides a consistent
  API whether using pynotify or gtkPopupNotify
  """

  def __init__(self, usePyNotify, params):
    self.timeout = params['timeout']
    self.usePyNotify = usePyNotify

    if self.usePyNotify:
      try:
        log.debug("Attempting to use pynotify")
        import pynotify
        self.notifier = pynotify
        self.notifier.init(params['appname'])
      except:
        log.warning("Unable to import pynotify. Using gtkPopupNotify instead")
        self.usePyNotify = False

    if not self.usePyNotify:
      log.debug("Importing gtkPopupNotify")
      import gtkPopupNotify, gtk
      for k in params.keys():
        log.debug("Popup param '%s': %s", k, params[k])
      self.notifier=gtkPopupNotify.NotificationStack(timeout=self.timeout)
      self.notifier.show_timeout = False
      self.notifier.edge_offset_x = params['xoff']
      self.notifier.edge_offset_y = params['yoff']
      self.notifier.corner = params['left'],params['top']
      self.notifier.max_popups = 1
      self.notifier.bg_color = gtk.gdk.Color(params['bg'])
      self.notifier.fg_color = gtk.gdk.Color(params['fg'])
      self.notifier.fontdesc = ("Sans Bold 10", "Sans 10", "Sans 10")

  def show(self, title, message):
    log.debug("Popup.show called")
    if self.usePyNotify:
      log.debug("Notifying with pynotifier")
      n=self.notifier.Notification(title,message,"call-start")
      n.set_timeout(self.timeout * 1000)
      n.show()
    else:
      # getting the current path depends on whether we're a compiled
      # binary, or a script being run through the interpreter
      # http://stackoverflow.com/questions/1511461/py2exe-and-the-file-system
      frozen = getattr(sys, 'frozen', '')
      if not frozen:
          # not frozen: in regular python interpreter
          approot = sys.path[0]
      elif frozen in ('dll', 'console_exe', 'windows_exe'):
          # py2exe:
          approot = os.path.dirname(sys.executable)
      elif frozen in ('macosx_app',):
          # py2app:
          # Notes on how to find stuff on MAC, by an expert (Bob Ippolito):
          # http://mail.python.org/pipermail/pythonmac-sig/2004-November/012121.html
          approot = os.environ['RESOURCEPATH']

      imagepath=os.path.join(approot, 'call-start.png')
      log.debug("Notifying with gtkPopupNotify (image at %s)", imagepath)
      self.notifier.new_popup(title=escape(title), message=escape(message), image=imagepath)
    return True

class CallPopHandler:
    """ Main application handler """

    pingtimeout = 5
    pinginterval = 120
    dbpath = os.path.expanduser('~/.callpoppy/callpoppy.db')
    lookupdigits = 10

    def __init__(self, extensions, popup):
        # set up connection to sqllite
        sqlconnection = sqlite.connect(self.dbpath)
        self.cursor = sqlconnection.cursor()
        self.extensions = extensions
        self.popup = popup
        for k in self.extensions.keys():
          log.debug("Extension configured: '%s': %s", k, self.extensions[k])

    def onDial(self, protocol, event):
        log.debug("Got event %s", event)
        if 'destination' in event:
          destination=event['destination'].lower()
          for s in self.extensions.keys():
            log.debug("Checking destination %s against extension %s", destination, s.lower())
            if destination.startswith(s.lower()):
              log.debug("Processing call for %s", s)
              if 'calleridnum' in event:
                cid=event['calleridnum']
              else :
                # earlier versions of Asterisk used callerid rather than calleridnum
                cid = event['callerid']
              cidname=self.lookupnumber(cid,event['calleridname'])
              extname=self.extensions[s]
              log.info("Call from %s (%s) for %s", cidname, cid, extname)
              self.popup.show("Incoming call for "+extname, cidname + "\n"+cid)

    def lookupnumber(self, cidnum, out):
        idx = cidnum[-self.lookupdigits:]
        log.debug("Looking up number '%s'", idx)
        try:
          self.cursor.execute('SELECT name FROM numbers WHERE tel = ?', (idx,))
          row = self.cursor.fetchone()
        except Exception as e:
          log.debug("Number not found in database: %s", e)
          return out
        if row:
          out = row[0]
        return out

    def onLogin(self, protocol):
        log.debug('Resetting reconnection delay')
        protocol.factory.resetDelay()
        df = protocol.registerEvent("Dial",self.onDial)
        self.timeouttask = task.LoopingCall(self.pinglink, protocol)
        self.timeouttask.start(self.pinginterval);
        return df

    def pinglink(self, protocol):
        def ontimeout():
            log.debug("Unexpected response or timeout waiting. Closing connection")
            if dc.active():
                dc.cancel()
            self.timeouttask.stop()
            protocol.transport.loseConnection()

        def canceltimeout(*val):
            if dc.active():
                dc.cancel()
            log.debug("Received pong. Cancelling timeout")
            log.debug("%s", val)

        def success(val):
            pass

        log.debug("Pinging server - setting timeout")
        dc = reactor.callLater(self.pingtimeout,ontimeout)
        df = protocol.ping()
        df.addBoth(canceltimeout)
        df.addCallback(success)
        df.addErrback(ontimeout)

def main():
    # initialise our notifier
    popup = Popup(conf['usePyNotify'], conf['popupparams'])
    # initialis our handler, passing the notifier to it
    handler = CallPopHandler(conf['extensions'], popup)
    # some handler configuration
    handler.dbpath = conf['dbfile']
    handler.lookupdigits = conf['lookupdigits']
    # initialise our factory
    factory = CallPopFactory(conf['username'], conf['secret'], conf['server'], conf['port'])



    factory.connect_callback=handler.onLogin
    factory.maxDelay = 600
    factory.connect()

def killapp(*args):
    reactor.stop()
    return True

if __name__ == '__main__':

    appname = 'callpoppy'

    # Keep our logs secret
    os.umask(0077);

    config = ConfigParser.ConfigParser({
      'port': '5038',
      'uselibnotify': 'True',
      'background': '#171717',
      'foreground': '#bbbbbb',
      'top': "0",
      'left': "0",
      'x-offset': "0",
      'y-offset': "0",
      'timeout': "6",
      'loglevel': "4",
      'logfile': os.path.expanduser('~/.callpoppy/callpoppy.log'),
      'dbfile': os.path.expanduser('~/.callpoppy/callpoppy.db'),
      'digits': "10"
      })

    config.optionxform = str
    conffile = os.path.expanduser('~/.callpoppy/config')
    conf = {}
    try:
      config.read(conffile)

      conf['server'] = config.get('Asterisk', 'server')
      conf['port'] = config.getint('Asterisk', 'port')
      conf['username'] = config.get('Asterisk', 'username')
      conf['secret'] = config.get('Asterisk', 'secret')

      conf['loglevel'] = config.getint('Logging', 'loglevel')
      conf['logfile'] = config.get('Logging', 'logfile')

      conf['dbfile'] = config.get('Database', 'dbfile')
      conf['lookupdigits'] = config.getint('Database', 'digits')

      conf['popupparams'] = {}
      conf['popupparams']['bg'] = config.get('Popup', 'background')
      conf['popupparams']['fg'] = config.get('Popup', 'foreground')
      conf['popupparams']['top'] = config.getboolean('Popup', 'top')
      conf['popupparams']['left'] = config.getboolean('Popup', 'left')
      conf['popupparams']['xoff'] = config.getint('Popup', 'x-offset')
      conf['popupparams']['yoff'] = config.getint('Popup', 'y-offset')
      conf['popupparams']['timeout'] = config.getint('Popup', 'timeout')
      conf['popupparams']['appname'] = appname

      conf['usePyNotify'] = config.getboolean('Popup', 'uselibnotify')

      ext = config.options('Extensions')

      conf['extensions'] = {}

      for s in ext:
        # annoyingly, ConfigParser.options returns all the defaults, so
        # we need to filter them out
        if s not in config.defaults().keys():
          conf['extensions'][s] = config.get('Extensions', s)

    except ConfigParser.Error as conferr:
      sys.exit(appname + " could not read the configuration file '" + conffile +"':\n" + conferr.__str__())

    # Set up logging
    log = logging.getLogger(appname)
    loglevels = [logging.CRITICAL, logging.ERROR, logging.WARNING, logging.INFO, logging.DEBUG]
    loglevel = loglevels[conf['loglevel'] - 1]
    log.setLevel(loglevel)

    # create log handler and set level. This creates a rotating log file
    lh = logging.handlers.RotatingFileHandler(conf['logfile'], 'a', 102400, 3)
    lh.setLevel(loglevel)

    logformat = logging.Formatter('%(asctime)s %(name)s: %(levelname)s %(message)s')
    lh.setFormatter(logformat)

    log.addHandler(lh)

    # set up logging from starpy
    logging.getLogger('AMI').setLevel(loglevel)
    logging.getLogger('AMI').addHandler(lh)

    log.info("Starting %s version %s", appname, __version__)
    log.debug("Configuration read from %s", conffile)
    log.debug("Configuration: %s", conf)

    # On Gnome, ensure the script exits when the user
    # logs out.
    if hasGnome:
      gnome.program_init (appname, "1.0")
      client = gnome.ui.master_client()
      client.connect("save-yourself", killapp)

    reactor.callWhenRunning(main)
    reactor.run()